backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "src/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "list", hint: "Skriv alltid eXAKT samma namn. Separate multiple authors by comma" }
      - { label: "Publish Date", name: "publishDate", widget: "string", hint: "dd Månad yyyy" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", hint: "Separate by comma"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: "src/assets" # Location where files will be stored in the repo
public_folder: "src/assets" # The src attribute for uploaded media
